### ISSUE TITLE
Isomorphic React and todo-app-modular example failing

### ISSUE THREAD

**Issue by mattfarina** [HewlettPackard/grommet#179]
Following the directions in the [Readme](https://github.com/HewlettPackard/grommet/tree/master/examples/todo-app-modular), everything was working until I reached step 4. Then I get the following error,

```sh
± node ssr/server.js

/Users/mfarina/Code/grommet/node_modules/babel-loader/index.js!/Users/mfarina/Code/grommet/node_modules/node-uuid/uuid.js:19
  if (typeof _global.require == 'function') {
                    ^
TypeError: Cannot read property 'require' of undefined
    at /Users/mfarina/Code/grommet/node_modules/babel-loader/index.js!/Users/mfarina/Code/grommet/node_modules/node-uuid/uuid.js:19:21
    at Object.<anonymous> (/Users/mfarina/Code/grommet/node_modules/babel-loader/index.js!/Users/mfarina/Code/grommet/node_modules/node-uuid/uuid.js:245:4)
    at Module._compile (/Users/mfarina/Code/grommet/examples/todo-app-modular/node_modules/enhanced-require/lib/Module.js:31:18)
    at exec (/Users/mfarina/Code/grommet/examples/todo-app-modular/node_modules/enhanced-require/lib/execModule.js:29:5)
    at RequireContext.theRequire (/Users/mfarina/Code/grommet/examples/todo-app-modular/node_modules/enhanced-require/lib/RequireContext.js:208:10)
    at Object.<anonymous> (/Users/mfarina/Code/grommet/node_modules/babel-loader/index.js!/Users/mfarina/Code/grommet/src/js/components/icons/status/OK.js:7:12)
    at Module._compile (/Users/mfarina/Code/grommet/examples/todo-app-modular/node_modules/enhanced-require/lib/Module.js:31:18)
    at exec (/Users/mfarina/Code/grommet/examples/todo-app-modular/node_modules/enhanced-require/lib/execModule.js:29:5)
    at RequireContext.theRequire (/Users/mfarina/Code/grommet/examples/todo-app-modular/node_modules/enhanced-require/lib/RequireContext.js:208:10)
    at Object.<anonymous> (/Users/mfarina/Code/grommet/node_modules/babel-loader/index.js!/Users/mfarina/Code/grommet/src/js/components/icons/Status.js:6:10)
```

I've tried this with both an exported and un-exported example.

Am I doing something wrong or is there a bug here?

**Comment by alansouzati** [comment]
I believe this is a bug, investigating it soon! sorry about that :(

**Comment by alansouzati** [comment]
It is fixed by https://github.com/HewlettPackard/grommet/commit/8a82f1e22ed07b12e5535c17970a1dfa2908bd46.

If you are using inside Grommet source code, you should be able to run that immediately. 

If you have exported the todo-app-modular and you are using the stable version, just run `npm update` inside your project and it should work.

It will be part of the next release of Grommet.

Thanks for reporting this! :+1:
