### ISSUE TITLE
gulp dist fails at 'test' task

### ISSUE THREAD

**Issue by cssberries** [HewlettPackard/grommet#42]
PROJECTS/grommet (master)
$ gulp dist
[00:24:04] Using gulpfile c:\PROJECTS\grommet\gulpfile.js
[00:24:04] Starting 'dist-preprocess'...
[00:24:04] Starting 'preprocess'...
[00:24:04] Starting 'clean'...
[00:24:04] Finished 'clean' after 307 ms
[00:24:04] Starting 'copy'...
[00:24:04] Finished 'copy' after 9.08 ms
[00:24:04] Starting 'jslint'...
[00:24:09] Finished 'jslint' after 5.05 s
[00:24:09] Starting 'scsslint'...
[00:24:09] Finished 'scsslint' after 4.76 μs
[00:24:09] Finished 'preprocess' after 5.37 s
[00:24:09] Starting 'dist-css'...
[00:24:10] Finished 'dist-css' after 546 ms
[00:24:10] Starting 'copy'...
[00:24:10] Finished 'copy' after 5.05 ms
[00:24:10] Starting 'test'...

c:\PROJECTS\grommet\node_modules\jsdom\lib\jsdom\utils.js:269
        const children = el._childNodes;
        ^^^^^
[00:24:10] 'test' errored after 604 ms
[00:24:10] SyntaxError: Use of const in strict mode.
    at Module._compile (module.js:439:25)
    at Object.require.extensions..js (c:\PROJECTS\grommet\src\utils\test\test-compiler.js:44:17)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (c:\PROJECTS\grommet\node_modules\jsdom\lib\jsdom.js:12:17)
    at Module._compile (module.js:456:26)
    at Object.require.extensions..js (c:\PROJECTS\grommet\src\utils\test\test-compiler.js:44:17)
    at Module.load (module.js:356:32)
[00:24:10] 'dist-preprocess' errored after 6.53 s
[00:24:10] Error: [object Object]
    at formatError (c:\Users\belovy\AppData\Roaming\npm\node_modules\gulp\bin\gulp.js:169:10)
    at Gulp.<anonymous> (c:\Users\belovy\AppData\Roaming\npm\node_modules\gulp\bin\gulp.js:195:15)
    at Gulp.emit (events.js:117:20)
    at Gulp.Orchestrator._emitTaskDone (c:\PROJECTS\grommet\node_modules\gulp\node_modules\orchestrator\index.js:264:8)
    at c:\PROJECTS\grommet\node_modules\gulp\node_modules\orchestrator\index.js:275:23
    at finish (c:\PROJECTS\grommet\node_modules\gulp\node_modules\orchestrator\lib\runTask.js:21:8)
    at cb (c:\PROJECTS\grommet\node_modules\gulp\node_modules\orchestrator\lib\runTask.js:29:3)
    at finish (c:\PROJECTS\grommet\node_modules\run-sequence\index.js:53:5)
    at Gulp.onError (c:\PROJECTS\grommet\node_modules\run-sequence\index.js:60:4)
    at Gulp.emit (events.js:117:20)

**Comment by alansouzati** [comment]
Hi @cssberries, can you describe more about your environment? Are you using es6 syntax at all?

I'm wondering if `const children = el._childNodes;` is coming from your app or from a dependency we use.

**Comment by cssberries** [comment]
I'm running on Windows 7 64bit.
I'm going though the steps shown in the video.

**Comment by alansouzati** [comment]
Ok thanks. So probably is a dependency of ours using ES6 format.

I will investigate that on windows. I was not expecting this issue. Let me get back to you soon.

**Comment by alansouzati** [comment]
Hi @cssberries , I've just tried in the same environment and using Windows 7 as well and I'm not able to reproduce this issue.

![screen shot 2015-06-16 at 4 42 47 pm](https://cloud.githubusercontent.com/assets/1207250/8196961/d1ff266c-1446-11e5-9413-508df3d5ef6e.png)

Can you confirm the Node and NPM version you are using? 

I'm using Node v0.12.4 and npm 2.10.1.

**Comment by cssberries** [comment]
Updating Node to v0.12.4 solves the issue.

Now I have Warning when running "coverage" task.
Should I open a new issue for that?

[09:47:10] Finished 'test' after 7.37 s
[09:47:10] Starting 'coverage'...
Done! You can checkout the report at test/coverage.html.
[09:47:13] Finished 'coverage' after 2.93 s
Warning: owner-based and parent-based contexts differ (values: `undefined` vs `pt-BR`) for key (locales) while mounting LoginForm (see: http://fb.me/react-context-by-parent)
Test failed: Error: connect ECONNREFUSED
    at exports._errnoException (util.js:746:11)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1010:19)

**Comment by alansouzati** [comment]
Well this warning is expected as part of React version 0.13. We are waiting for the release of React 0.14 to get this warning gone. You should not worry about it. But I would not expect your test to fail.

Based on the logs it seems to be related to a network issue. `Error: connect ECONNREFUSED`.

Are you under a proxied network?

**Comment by cssberries** [comment]
I am behind a proxy server but NPM is configured as expected.

New issue:
I managed to run the "dev" task successfully but when I navigate to "http://localhost:9000/webpack-dev-server/" - nothing happens.

$ gulp dev                                                                                                                                                   
[20:29:19] Using gulpfile c:\PROJECTS\grommet\gulpfile.js                                                                                                    
[20:29:19] Starting 'preprocess'...                                                                                                                          
[20:29:19] Starting 'clean'...                                                                                                                               
[20:29:19] Finished 'clean' after 124 ms                                                                                                                     
[20:29:19] Starting 'copy'...                                                                                                                                
[20:29:19] Finished 'copy' after 11 ms                                                                                                                       
[20:29:19] Starting 'jslint'...                                                                                                                              
[20:29:25] Finished 'jslint' after 5.5 s                                                                                                                     
[20:29:25] Starting 'scsslint'...                                                                                                                            
[20:29:25] Finished 'scsslint' after 8.43 μs                                                                                                                 
[20:29:25] Finished 'preprocess' after 5.65 s                                                                                                                
[20:29:25] Starting 'dev'...                                                                                                                                 
[20:29:25] Finished 'dev' after 62 ms                                                                                                                        
[webpack-dev-server] started: Browse to http://localhost:undefined/webpack-dev-server/                                                                       
Hash: ef865046a49a9f9bdd63                                                                                                                                   
Version: webpack 1.9.10                                                                                                                                      
Time: 2430ms                                                                                                                                                 
   Asset     Size  Chunks             Chunk Names                                                                                                            
index.js  1.76 MB    0, 1  [emitted]  styles, app                                                                                                            
chunk    {0} index.js (styles) 138 kB [rendered]                                                                                                             
    [0] multi styles 40 bytes {0} [built]                                                                                                                    
    [1] (webpack)/hot/dev-server.js 1.83 kB {0} {1} [built]                                                                                                  
    [2] (webpack)/hot/log-apply-result.js 813 bytes {0} {1} [built]                                                                                          
    [3] ./src/scss/grommet-core/index.scss 1.19 kB {0} [built]                                                                                               
    [4] ./~/css-loader!./~/sass-loader?outputStyle=expanded&includePaths[]=c:/PROJECTS/grommet/node_modules!./src/scss/grommet-core/index.scss 126 kB {0} [bu
ilt]                                                                                                                                                         
    [5] ./~/css-loader/lib/css-base.js 1.51 kB {0} [built]                                                                                                   
    [6] ./~/style-loader/addStyles.js 6.02 kB {0} [built]                                                                                                    
chunk    {1} index.js (app) 481 kB [rendered]                                                                                                                
    [0] multi app 40 bytes {1} [built]                                                                                                                       
    [1] (webpack)/hot/dev-server.js 1.83 kB {0} {1} [built]                                                                                                  
    [2] (webpack)/hot/log-apply-result.js 813 bytes {0} {1} [built]                                                                                          
    [7] ./src/js/index.js 2.18 kB {1} [built]                                                                                                                
    [8] ./src/js/components/Tile.js 1.06 kB {1} [built]                                                                                                      
    [9] external "React" 42 bytes {1} [not cacheable]                                                                                                        
   [10] ./src/js/components/App.js 1.18 kB {1} [built]                                                                                                       
   [11] ./src/js/mixins/GrommetIntlMixin.js 1.92 kB {1} [built]                                                                                              
   [12] ./~/intl/Intl.js 130 kB {1} [built]                                                                                                                  
   [13] ./~/intl/locale-data/json/en-US.json 19.6 kB {1} [built]                                                                                             
   [14] ./~/intl/locale-data/json/pt-BR.json 21.7 kB {1} [built]                                                                                             
   [15] ./~/react-intl/index.js 1.28 kB {1} [built]                                                                                                          
   [16] ./~/react-intl/lib/react-intl.js 1.27 kB {1} [built]                                                                                                 
   [17] ./~/react-intl/lib/components/time.js 1.16 kB {1} [built]                                                                                            
   [18] ./~/react-intl/lib/react.js 311 bytes {1} [built]                                                                                                    
   [19] ./~/react-intl/lib/mixin.js 5.38 kB {1} [built]                                                                                                      
   [20] ./~/react-intl/~/intl-messageformat/index.js 553 bytes {1} [built]                                                                                   
   [21] ./~/react-intl/~/intl-messageformat/lib/main.js 288 bytes {1} [built]                                                                                
   [22] ./~/react-intl/~/intl-messageformat/lib/core.js 8.36 kB {1} [built]                                                                                  
   [23] ./~/react-intl/~/intl-messageformat/lib/utils.js 710 bytes {1} [built]                                                                               
   [24] ./~/react-intl/~/intl-messageformat/lib/es5.js 1.25 kB {1} [built]                                                                                   
   [25] ./~/react-intl/~/intl-messageformat/lib/compiler.js 6.07 kB {1} [built]                                                                              
   [26] ./~/react-intl/~/intl-messageformat/~/intl-messageformat-parser/index.js 108 bytes {1} [built]                                                       
   [27] ./~/react-intl/~/intl-messageformat/~/intl-messageformat-parser/lib/parser.js 36.8 kB {1} [built]                                                    
   [28] ./~/react-intl/~/intl-messageformat/lib/en.js 363 bytes {1} [built]                                                                                  
   [29] ./lib/locales (ignored) 15 bytes {1}                                                                                                                 
   [30] ./~/react-intl/~/intl-relativeformat/index.js 557 bytes {1} [built]                                                                                  
   [31] ./~/react-intl/~/intl-relativeformat/lib/main.js 288 bytes {1} [built]                                                                               
   [32] ./~/react-intl/~/intl-relativeformat/lib/core.js 9.64 kB {1} [built]                                                                                 
   [33] ./~/react-intl/~/intl-relativeformat/lib/diff.js 1.11 kB {1} [built]                                                                                 
   [34] ./~/react-intl/~/intl-relativeformat/lib/es5.js 1.88 kB {1} [built]                                                                                  
   [35] ./~/react-intl/~/intl-relativeformat/lib/en.js 1.53 kB {1} [built]                                                                                   
   [36] ./lib/locales (ignored) 15 bytes {1}                                                                                                                 
   [37] ./~/react-intl/~/intl-format-cache/index.js 110 bytes {1} [built]                                                                                    
   [38] ./~/react-intl/~/intl-format-cache/lib/memoizer.js 1.76 kB {1} [built]                                                                               
   [39] ./~/react-intl/~/intl-format-cache/lib/es5.js 1.06 kB {1} [built]                                                                                    
   [40] ./~/react-intl/lib/en.js 1.53 kB {1} [built]                                                                                                         
   [41] ./~/react-intl/lib/components/date.js 1.16 kB {1} [built]                                                                                            
   [42] ./~/react-intl/lib/components/relative.js 1.19 kB {1} [built]                                                                                        
   [43] ./~/react-intl/lib/components/number.js 1.24 kB {1} [built]                                                                                          
   [44] ./~/react-intl/lib/components/message.js 3.09 kB {1} [built]                                                                                         
   [45] ./~/react-intl/lib/components/html-message.js 2.36 kB {1} [built]                                                                                    
   [46] ./~/react-intl/lib/escape.js 705 bytes {1} [built]                                                                                                   
   [47] ./lib/locales (ignored) 15 bytes {1}                                                                                                                 
   [48] ./src/js/messages ^\.\/.*$ 214 bytes {1} [optional] [built]                                                                                          
   [49] ./src/js/messages/en-US.js 930 bytes {1} [built]                                                                                                     
   [50] ./src/js/messages/pt-BR.js 946 bytes {1} [optional] [built]                                                                                          
   [51] ./src/js/components/Button.js 1.33 kB {1} [built]                                                                                                    
   [52] ./src/js/components/CheckBox.js 1.35 kB {1} [built]                                                                                                  
   [53] ./src/js/components/Document.js 923 bytes {1} [built]                                                                                                
   [54] ./src/js/components/Donut.js 9.95 kB {1} [built]                                                                                                     
   [55] ./src/js/components/Legend.js 3.71 kB {1} [built]                                                                                                    
   [56] ./src/js/components/Footer.js 2.52 kB {1} [built]                                                                                                    
   [57] ./src/js/components/icons/Top.js 840 bytes {1} [built]                                                                                               
   [58] ./src/js/components/Form.js 1.1 kB {1} [built]                                                                                                       
   [59] ./src/js/components/FormField.js 2.67 kB {1} [built]                                                                                                 
   [60] ./src/js/components/Header.js 3.04 kB {1} [built]                                                                                                    
   [61] ./src/js/components/Label.js 740 bytes {1} [built]                                                                                                   
   [62] ./src/js/components/Login.js 1.69 kB {1} [built]                                                                                                     
   [63] ./src/js/components/LoginForm.js 3.34 kB {1} [built]                                                                                                 
   [64] ./src/js/components/Menu.js 9.14 kB {1} [built]                                                                                                      
   [65] ./src/js/mixins/Overlay.js 3.12 kB {1} [built]                                                                                                       
   [66] ./src/js/utils/DOM.js 509 bytes {1} [built]                                                                                                          
   [67] ./src/js/mixins/ReactLayeredComponent.js 1.2 kB {1} [built]                                                                                          
   [68] ./src/js/mixins/KeyboardAccelerators.js 2.85 kB {1} [built]                                                                                          
   [69] ./src/js/components/icons/More.js 864 bytes {1} [built]                                                                                              
   [70] ./src/js/components/icons/DropCaret.js 662 bytes {1} [built]                                                                                         
   [71] ./src/js/components/Meter.js 18.7 kB {1} [built]                                                                                                     
   [72] ./src/js/components/Panel.js 846 bytes {1} [built]                                                                                                   
   [73] ./src/js/components/RadioButton.js 1.31 kB {1} [built]                                                                                               
   [74] ./src/js/components/Search.js 9.86 kB {1} [built]                                                                                                    
   [75] ./src/js/components/icons/Search.js 764 bytes {1} [built]                                                                                            
   [76] ./src/js/components/SearchInput.js 6.68 kB {1} [built]                                                                                               
   [77] ./src/js/components/Section.js 1.68 kB {1} [built]                                                                                                   
   [78] ./src/js/components/Table.js 5.2 kB {1} [built]                                                                                                      
   [79] ./src/js/components/icons/Spinning.js 901 bytes {1} [built]                                                                                          
   [80] ./src/js/mixins/InfiniteScroll.js 1.88 kB {1} [built]                                                                                                
   [81] ./src/js/components/Tiles.js 1.98 kB {1} [built]                                                                                                     
   [82] ./src/js/components/Title.js 552 bytes {1} [built]                                                                                                   
   [83] ./src/js/components/Object.js 2.27 kB {1} [built]                                                                                                    
   [84] ./src/js/components/TBD.js 319 bytes {1} [built]                                                                                                     
   [85] ./src/js/components/icons/Clear.js 758 bytes {1} [built]                                                                                             
   [86] ./src/js/components/icons/DragHandle.js 1.32 kB {1} [built]                                                                                          
   [87] ./src/js/components/icons/Edit.js 1.49 kB {1} [built]                                                                                                
   [88] ./src/js/components/icons/Filter.js 1.21 kB {1} [built]                                                                                              
   [89] ./src/js/components/icons/Help.js 770 bytes {1} [built]                                                                                              
   [90] ./src/js/components/icons/Left.js 743 bytes {1} [built]                                                                                              
   [91] ./src/js/components/icons/Right.js 746 bytes {1} [built]                                                                                             
   [92] ./src/js/components/icons/SearchPlus.js 1.03 kB {1} [built]                                                                                          
   [93] ./src/js/components/icons/Status.js 1.88 kB {1} [built]                                                                                              
   [94] ./src/js/components/icons/status/OK.js 1.31 kB {1} [built]                                                                                           
   [95] ./src/js/components/icons/status/ErrorStatus.js 866 bytes {1} [built]                                                                                
   [96] ./src/js/components/icons/status/Warning.js 1.42 kB {1} [built]                                                                                      
   [97] ./src/js/components/icons/status/Disabled.js 864 bytes {1} [built]                                                                                   
   [98] ./src/js/components/icons/status/Unknown.js 2.39 kB {1} [built]                                                                                      
   [99] ./src/js/components/icons/status/Label.js 663 bytes {1} [built]                                                                                      
  [100] ./src/js/actions/Actions.js 788 bytes {1} [built]                                                                                                    
  [101] ./~/reflux/index.js 35 bytes {1} [built]                                                                                                             
  [102] ./~/reflux/src/index.js 2.6 kB {1} [built]                                                                                                           
  [103] ./~/reflux/src/listenTo.js 1.5 kB {1} [built]                                                                                                        
  [104] ./~/reflux/src/ActionMethods.js 140 bytes {1} [built]                                                                                                
  [105] ./~/reflux/src/ListenerMethods.js 8.78 kB {1} [built]                                                                                                
  [106] ./~/reflux/src/utils.js 1.76 kB {1} [built]                                                                                                          
  [107] ./~/reflux/~/eventemitter3/index.js 6.08 kB {1} [built]                                                                                              
  [108] ./~/reflux/~/native-promise-only/npo.js 3.57 kB {1} [built]                                                                                          
  [109] ./~/node-libs-browser/~/timers-browserify/main.js 2.1 kB {1} [built]                                                                                 
  [110] ./~/node-libs-browser/~/process/browser.js 2.02 kB {1} [built]                                                                                       
  [111] (webpack)/buildin/amd-options.js 43 bytes {1} [built]                                                                                                
  [112] ./~/reflux/src/joins.js 3.75 kB {1} [built]                                                                                                          
  [113] ./~/reflux/src/createStore.js 2.04 kB {1} [built]                                                                                                    
  [114] ./~/reflux/src/Keep.js 263 bytes {1} [built]                                                                                                         
  [115] ./~/reflux/src/mixer.js 1.71 kB {1} [built]                                                                                                          
  [116] ./~/reflux/src/bindMethods.js 689 bytes {1} [built]                                                                                                  
  [117] ./~/reflux/src/PublisherMethods.js 5.83 kB {1} [built]                                                                                               
  [118] ./~/reflux/src/StoreMethods.js 138 bytes {1} [built]                                                                                                 
  [119] ./~/reflux/src/createAction.js 1.98 kB {1} [built]                                                                                                   
  [120] ./~/reflux/src/connect.js 942 bytes {1} [built]                                                                                                      
  [121] ./~/reflux/src/connectFilter.js 1.34 kB {1} [built]                                                                                                  
  [122] ./~/reflux/src/ListenerMixin.js 568 bytes {1} [built]                                                                                                
  [123] ./~/reflux/src/listenToMany.js 1.35 kB {1} [built]                                                                                                   
  [124] ./src/js/utils/Rest.js 1.91 kB {1} [built]                                                                                                           
  [125] ./~/superagent/lib/client.js 23.6 kB {1} [built]                                                                                                     
  [126] ./~/superagent/~/component-emitter/index.js 3 kB {1} [built]                                                                                         
  [127] ./~/superagent/~/reduce-component/index.js 405 bytes {1} [built]                                                                                     
  [128] ./src/js/stores/SessionStore.js 1.95 kB {1} [built]                                                                                                  
  [129] ./src/js/utils/Cookies.js 2.73 kB {1} [built]                                                                                                        
webpack: bundle is now VALID.

**Comment by bryanjacquot** [comment]
It's a bit hidden, but this line is the key thing

```
[webpack-dev-server] started: Browse to http://localhost:undefined/webpack-dev-server/
```

If you point your browser at **http://localhost:undefined/webpack-dev-server/**you should see the app you're running.

**Comment by cssberries** [comment]
Well, it takes me to the google's search result page.

**Comment by bryanjacquot** [comment]
I should have looked closer, the "port" part of the URL is "undefined".  I'll need Alan to look at that.

**Comment by alansouzati** [comment]
The default port is 9000, I'm not sure why yours is showing as undefined. In your `gulpfile.js` could you please make sure you have the following entry in your `opts`: 

```javascript
var opts = {
   ...
   devServerPort: 9000,
   ...
};
```

If you have it there, your dev server should be available at http://localhost:9000/webpack-dev-server/

**Comment by alansouzati** [comment]
If you see the Grommet logo loading forever you might be experience the webpack problem. I'm going to create a separate issue for this and post it here so that you understand.

**Comment by alansouzati** [comment]
#44

**Comment by cssberries** [comment]
Nope, I don't have the "devServerPort: 9000" entry.
I added it and got this:

![image](https://cloud.githubusercontent.com/assets/2432131/8216291/47324188-153e-11e5-8c19-0e1b446c3d6b.png)

**Comment by alansouzati** [comment]
Hum, interesting. I guess I know what's going on. Where are you trying to run `gulp dev`? At grommet root folder?

I believe you need to run `gulp dev` inside the `docs` folder. I remember you trying to watch the video on How to Contribute to Grommet, and I believe I mention that in the video. There is no UI to be server for the grommet root folder, that's why I think you are getting the not found stuff.

**Comment by bryanjacquot** [comment]
Alan, would it make sense to change the gulp dev task in the root folder to instruct them where the right place to run 'gulp dev'.

**Comment by alansouzati** [comment]
Good point. Will work on that.

**Comment by alansouzati** [comment]
Done! 

https://github.com/HewlettPackard/grommet/commit/f44c6b8bc04c302c3e9db6f0d62a21ef1f3a572a

@cssberries, if you sync your Fork you should be able to see the message now.

**Comment by cssberries** [comment]
Finally I can see the right screen!

And some errors from Chrom's console:
GET http://localhost:8002/favicon.ico 404 (Not Found)
dev-server.js?b7b7:57 [HMR] Waiting for update signal from WDS...
warning.js?8bc8:48 Warning: Failed propType: Invalid prop `handler` of type `object` supplied to `Route`, expected `function`.
warning.js?8bc8:48 Warning: Invalid undefined `handler` of type `object` supplied to `UnknownComponent`, expected `function`.

**Comment by alansouzati** [comment]
Cool, I can see possible Pull Requests here. :+1:
