### ISSUE TITLE
slackin error

### ISSUE THREAD

**Issue by mattfarina** [HewlettPackard/grommet#43]
When visiting *http://grommet.io/slackin* I see the error:
```
Error: connect ECONNREFUSED
   at errnoException (net.js:901:11)
   at Object.afterConnect [as oncomplete] (net.js:892:19) 
```

Note, I noticed *https://grommet.io/slackin* doesn't work. Is that intentional?

**Comment by bryanjacquot** [comment]
Thanks.  We saw this yesterday and restarted service.  Have now found the exception in Slackin, but aren't sure why yet.

```
/usr/local/lib/node_modules/slackin/node/slack.js:70
        res.body.channels.forEach(function (channel) {
                          ^
TypeError: Cannot call method 'forEach' of undefined
    at SlackData.onres (/usr/local/lib/node_modules/slackin/node/slack.js:70:27)
    at /usr/local/lib/node_modules/slackin/node/slack.js:41:17
    at Request.callback (/usr/local/lib/node_modules/slackin/node_modules/superagent/lib/node/index.js:746:30)
    at Request.<anonymous> (/usr/local/lib/node_modules/slackin/node_modules/superagent/lib/node/index.js:135:10)
    at Request.EventEmitter.emit (events.js:95:17)
    at Stream.<anonymous> (/usr/local/lib/node_modules/slackin/node_modules/superagent/lib/node/index.js:938:12)
    at Stream.EventEmitter.emit (events.js:117:20)
    at Unzip.<anonymous> (/usr/local/lib/node_modules/slackin/node_modules/superagent/lib/node/utils.js:124:12)
    at Unzip.EventEmitter.emit (events.js:117:20)
    at _stream_readable.js:920:16
```

**Comment by alansouzati** [comment]
It seems to be related to sending invite requests without a Channel. I added a safety check on our end and I will submit a Pull Request to Slackin today to get it fixed, hopefully :smile: 

I believe this issue is fixed not, so I'm going to close it. If it happens again, feel free to reopen.

**Comment by purplelightsaber** [comment]
I am getting the same error on the now logs. The following just repeats:

▲ Deploying image
02/03/17 5:47:17 PM
▲ Container started
02/03/17 5:47:20 PM
Fri Feb 03 2017 23:47:19 GMT+0000 (UTC) – fetching
02/03/17 5:47:20 PM
/srv/www/dist/slack.js:54
          throw err;
          ^

Error: connect ECONNREFUSED 127.0.0.1:443
    at Object.exports._errnoException (util.js:1023:11)
    at exports._exceptionWithHostPort (util.js:1046:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1090:14)
02/03/17 5:47:20 PM
Fri Feb 03 2017 23:47:19 GMT+0000 (UTC) – listening on d44624e2aabd:30
