### ISSUE TITLE
gulp dist

### ISSUE THREAD

**Issue by tran2519** [HewlettPackard/grommet#62]
My environment is windows, nodejs version is 0.12.4.  I ran into this problem when running 'gulp dist':

module.js:338
    throw err;
          ^
Error: Cannot find module './lib/install'
    at Function.Module._resolveFilename (module.js:336:15)
    at Function.Module._load (module.js:278:25)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (C:\Users\trankim1\git\grommet\node_modules\selenium-
tandalone\index.js:2:12)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)

Alan Souzati noted: "we are running integration tests now (started yesterday), that’s why you see the selenium dependency. It seems it is problematic with windows. "

**Comment by tran2519** [comment]
Thanks @TiagoJustino for helping me solve the issues. 
I can bring up the examples/medium-app locally.  But still got problems to bring up the server. Here is the error when I run grommet/examples/server gulp dev:

trankim1@TRANKIM11 ~/git/grommet/examples/server
$ gulp dev
[08:57:21] Using gulpfile ~\git\grommet\examples\server\gulpfile.js
[08:57:21] Starting 'dev'...
[08:57:21] Finished 'dev' after 2.09 ms
[08:57:22] [nodemon] v1.3.7
[08:57:22] [nodemon] to restart at any time, enter `rs`
[08:57:22] [nodemon] watching: *.*
[08:57:22] [nodemon] starting `node server.js`
events.js:85
      throw er; // Unhandled 'error' event
            ^
Error: spawn cmd ENOENT
    at exports._errnoException (util.js:746:11)
    at Process.ChildProcess._handle.onexit (child_process.js:1053:32)
    at child_process.js:1144:20
    at process._tickCallback (node.js:355:11)

**Comment by tran2519** [comment]
Thanks @TiagoJustino for helping me solve the issues. 
I can bring up the examples/medium-app locally.  But still got problems to bring up the server. Here is the error when I run grommet/examples/server gulp dev:

trankim1@TRANKIM11 ~/git/grommet/examples/server
$ gulp dev
[08:57:21] Using gulpfile ~\git\grommet\examples\server\gulpfile.js
[08:57:21] Starting 'dev'...
[08:57:21] Finished 'dev' after 2.09 ms
[08:57:22] [nodemon] v1.3.7
[08:57:22] [nodemon] to restart at any time, enter `rs`
[08:57:22] [nodemon] watching: *.*
[08:57:22] [nodemon] starting `node server.js`
events.js:85
      throw er; // Unhandled 'error' event
            ^
Error: spawn cmd ENOENT
    at exports._errnoException (util.js:746:11)
    at Process.ChildProcess._handle.onexit (child_process.js:1053:32)
    at child_process.js:1144:20
    at process._tickCallback (node.js:355:11)

**Comment by alansouzati** [comment]
Hi, I need to tweak the example server to avoid running `gulp dev` there. It is not supported. 

Please refer to [Running Example Server](https://github.com/HewlettPackard/grommet/wiki/Running-the-example-server) to learn how to start the example server.

**Comment by bryanjacquot** [comment]
@alansouzati would it make sense to provide a `gulp dev` task in examples/server to simply run the `node server` command?  I use this quite a bit.  Using the same command (even if it does different things under the covers) in each area/example would be beneficial.

**Comment by alansouzati** [comment]
Cool, i will work on that and update both the wiki and the code.

**Comment by tran2519** [comment]
Thanks, @bryanjacquot and @alansouzati.
'node server' shows me all the rest calls.  By the browser  (chrome, IE11) throws this error:
Proxy error. Could not proxy to content base target!
cannot proxy to http://localhost:8000 (socket hang up)
 Note:  I do not use Proxy server in my browser LAN Settings.  I use automatic configuration scrips http://autocache.hp.com

![grommet](https://cloud.githubusercontent.com/assets/13039669/8460129/cd6b83e8-1fd6-11e5-9d41-514f90d0aac0.JPG)

**Comment by alansouzati** [comment]
Could you please make sure that your node server is running? if you run `node server`, this is a blocking process, meaning if you close the command line, it will stop the server.

**Comment by tran2519** [comment]
@alansouzati  After a couple of minutes, the browser refreshed itself and it works .  Thanks.
